services:
  rabbitmq:
    image: rabbitmq:3.13
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: avg
      RABBITMQ_DEFAULT_PASS: avg

  wms:
    build: .
    container_name: wms
    environment:
      - RABBIT_URL=amqp://avg:avg@rabbitmq:5672
      - LOG_SERVER_URL=http://host.docker.internal:7070/log
